- worker-message-prioritization-rerouting/src/main/java/com/github/workerframework/workermessageprioritization/rerouting/StagingQueueCreator.java
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=625207
> 625207: Additonal logging

- worker-message-prioritization-distribution-container/pom.xml
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=614205
> US614205: rename docker image

- worker-message-prioritization-distribution-container/pom.xml
Fix this https://github.com/WorkerFramework/worker-message-prioritization/commit/6b0524756f32a8fe00f3b2462bb2e8f5259b6740
> Fix previous commit

- pom.xml
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=627175
> D627175: Update downstream dependencies

- pom.xml
- worker-message-prioritization-distribution-container/README.md
- worker-message-prioritization-distribution-container/pom.xml
- worker-message-prioritization-distribution/src/main/java/com/github/workerframework/workermessageprioritization/redistribution/config/MessageDistributorConfig.java
- worker-message-prioritization-distribution/src/main/java/com/github/workerframework/workermessageprioritization/redistribution/shovel/ShovelApplication.java
- worker-message-prioritization-rerouting/README.md
- worker-message-prioritization-rerouting/src/main/java/com/github/workerframework/workermessageprioritization/rerouting/MessageRouter.java
- worker-message-prioritization-rerouting/src/main/java/com/github/workerframework/workermessageprioritization/rerouting/MessageRouterSingleton.java
- worker-message-prioritization-rerouting/src/main/java/com/github/workerframework/workermessageprioritization/rerouting/reroutedeciders/AlwaysRerouteDecider.java
- worker-message-prioritization-rerouting/src/main/java/com/github/workerframework/workermessageprioritization/rerouting/reroutedeciders/RerouteDecider.java
- worker-message-prioritization-rerouting/src/main/java/com/github/workerframework/workermessageprioritization/rerouting/reroutedeciders/TargetQueueCapacityRerouteDecider.java
- worker-message-prioritization-rerouting/src/test/java/com/github/workerframework/workermessageprioritization/rerouting/MessageRouterTests.java
- worker-message-prioritization-target-capacity-calculators/pom.xml
- worker-message-prioritization-target-capacity-calculators/src/main/java/com/github/workerframework/workermessageprioritization/targetcapacitycalculators/K8sTargetQueueCapacityProvider.java
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=614207
> 614207: Add K8s implementation of target queue capacity provider

- worker-message-prioritization-distribution/src/main/java/com/github/workerframework/workermessageprioritization/redistribution/shovel/ShovelDistributor.java
- worker-message-prioritization-distribution/src/main/java/com/github/workerframework/workermessageprioritization/redistribution/shovel/ShovelStateChecker.java
- worker-message-prioritization-distribution/src/test/java/com/github/workerframework/workermessageprioritization/redistribution/ShovelStateCheckerIT.java
- worker-message-prioritization-rabbitmq/src/main/java/com/github/workerframework/workermessageprioritization/rabbitmq/RabbitManagementApi.java
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=632128
> 632128: Ensure proper shutdown + additional failure handling

- worker-message-prioritization-distribution-container/pom.xml
- worker-message-prioritization-distribution/src/main/java/com/github/workerframework/workermessageprioritization/redistribution/config/MessageDistributorConfig.java
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=634150
> D634150: Fortify issues

- worker-message-prioritization-distribution/src/main/java/com/github/workerframework/workermessageprioritization/redistribution/config/MessageDistributorConfig.java
- worker-message-prioritization-distribution/src/main/java/com/github/workerframework/workermessageprioritization/redistribution/shovel/ShovelApplication.java
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=650102
> D650102: Fortify Apollo BackEnd Services (Gamma) scan

- worker-message-prioritization-rabbitmq/src/main/java/com/github/workerframework/workermessageprioritization/rabbitmq/HealthCheckApi.java
- worker-message-prioritization-rerouting/src/main/java/com/github/workerframework/workermessageprioritization/rerouting/MessageRouterSingleton.java
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=632159
> 632159: Add healthcheck to MessageRouterSingleton

- worker-message-prioritization-distribution/pom.xml
- worker-message-prioritization-distribution/src/main/java/com/github/workerframework/workermessageprioritization/redistribution/shovel/CorruptedShovelChecker.java
- worker-message-prioritization-distribution/src/main/java/com/github/workerframework/workermessageprioritization/redistribution/shovel/ShovelApplication.java
- worker-message-prioritization-distribution/src/main/java/com/github/workerframework/workermessageprioritization/redistribution/shovel/ShovelDistributor.java
- worker-message-prioritization-distribution/src/test/java/com/github/workerframework/workermessageprioritization/redistribution/DistributorTestBase.java
- worker-message-prioritization-distribution/src/test/java/com/github/workerframework/workermessageprioritization/redistribution/ShovelDistributorIT.java
- worker-message-prioritization-distribution/src/test/java/com/github/workerframework/workermessageprioritization/redistribution/shovel/CorruptedShovelCheckerTest.java
- worker-message-prioritization-rabbitmq/src/main/java/com/github/workerframework/workermessageprioritization/rabbitmq/Node.java
- worker-message-prioritization-rabbitmq/src/main/java/com/github/workerframework/workermessageprioritization/rabbitmq/NodesApi.java
- worker-message-prioritization-rabbitmq/src/main/java/com/github/workerframework/workermessageprioritization/rabbitmq/ShovelsApi.java
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=680005
> 680005: Send delete corrupted shovel request to all nodes

- release-notes-1.0.1.md
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=693039
> 693039: Release prep

- release-notes-1.1.0.md
- worker-message-prioritization-distribution-container/pom.xml
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=708042
> D708042: Update to run on java 17

- release-notes-1.2.0.md
- worker-message-prioritization-distribution/src/main/java/com/github/workerframework/workermessageprioritization/redistribution/shovel/NonRunningShovelChecker.java
- worker-message-prioritization-distribution/src/main/java/com/github/workerframework/workermessageprioritization/redistribution/shovel/ShovelDistributor.java
- worker-message-prioritization-distribution/src/main/java/com/github/workerframework/workermessageprioritization/redistribution/shovel/ShovelRepairer.java
- worker-message-prioritization-distribution/src/main/java/com/github/workerframework/workermessageprioritization/redistribution/shovel/ShovelRunningTooLongChecker.java
- worker-message-prioritization-distribution/src/test/java/com/github/workerframework/workermessageprioritization/redistribution/DistributorTestBase.java
- worker-message-prioritization-distribution/src/test/java/com/github/workerframework/workermessageprioritization/redistribution/NonRunningShovelCheckerIT.java
- worker-message-prioritization-distribution/src/test/java/com/github/workerframework/workermessageprioritization/redistribution/ShovelRepairerIT.java
- worker-message-prioritization-distribution/src/test/java/com/github/workerframework/workermessageprioritization/redistribution/ShovelRunningTooLongCheckerIT.java
- worker-message-prioritization-rabbitmq/src/main/java/com/github/workerframework/workermessageprioritization/rabbitmq/CommonShovelProps.java
- worker-message-prioritization-rabbitmq/src/main/java/com/github/workerframework/workermessageprioritization/rabbitmq/RetrievedShovel.java
- worker-message-prioritization-rabbitmq/src/main/java/com/github/workerframework/workermessageprioritization/rabbitmq/ShovelToCreate.java
- worker-message-prioritization-rabbitmq/src/main/java/com/github/workerframework/workermessageprioritization/rabbitmq/ShovelsApi.java
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=714101
> 714101: Fix for issue where shovels were not getting restarted

- release-notes-1.2.0.md
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=711116
> 711116: Update release notes

- worker-message-prioritization-target-capacity-calculators/src/main/java/com/github/workerframework/workermessageprioritization/targetqueue/K8sTargetQueueSettingsProvider.java
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=692066
> US692066: Handle NumberFormatException when converting labels to longs

- worker-message-prioritization-distribution/src/main/java/com/github/workerframework/workermessageprioritization/redistribution/shovel/ShovelDistributor.java
- worker-message-prioritization-rabbitmq/src/main/java/com/github/workerframework/workermessageprioritization/rabbitmq/ShovelToCreate.java
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=691054
> US691054: Set src-prefetch-count shovel property

- release-notes-1.2.1.md
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=769058
> US769058: Update release notes

- pom.xml
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=773032
> US773032: Update guava to 32.1.2

- pom.xml
- worker-message-prioritization-rabbitmq/pom.xml
- worker-message-prioritization-rerouting/pom.xml
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=773019
> US773019: Upgrade okio

- pom.xml
- worker-message-prioritization-rerouting/pom.xml
This reverts commit b094ee1b23793015fcbbabb70706d5171ca7c2aa.
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=773019
> US773019: Revert "US773019: Upgrade okio (#57)"

- worker-message-prioritization-target-capacity-calculators/src/main/java/com/github/workerframework/workermessageprioritization/targetqueue/TunedTargetQueueLengthProvider.java
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=859128
> I859128: CAF_QUEUE_PROCESSING_TIME_GOAL_SECONDS not being respected

- pom.xml
- release-notes-1.4.0.md
- worker-message-prioritization-distribution-container/src/test/java/com/github/workerframework/workermessageprioritization/redistribution/DistributorTestBase.java
- worker-message-prioritization-distribution/src/main/java/com/github/workerframework/workermessageprioritization/redistribution/DistributorModule.java
- worker-message-prioritization-distribution/src/main/java/com/github/workerframework/workermessageprioritization/redistribution/MessageDistributor.java
- worker-message-prioritization-distribution/src/main/java/com/github/workerframework/workermessageprioritization/redistribution/lowlevel/LowLevelDistributor.java
- worker-message-prioritization-distribution/src/test/java/com/github/workerframework/workermessageprioritization/redistribution/DistributorTestBase.java
- worker-message-prioritization-distribution/src/test/java/com/github/workerframework/workermessageprioritization/redistribution/TunedTargetQueueIT.java
- worker-message-prioritization-rabbitmq/pom.xml
- worker-message-prioritization-rabbitmq/src/main/java/com/github/workerframework/workermessageprioritization/rabbitmq/GsonConfigurator.java
- worker-message-prioritization-rabbitmq/src/main/java/com/github/workerframework/workermessageprioritization/rabbitmq/HealthCheckApi.java
- worker-message-prioritization-rabbitmq/src/main/java/com/github/workerframework/workermessageprioritization/rabbitmq/HealthCheckApiImpl.java
- worker-message-prioritization-rabbitmq/src/main/java/com/github/workerframework/workermessageprioritization/rabbitmq/NodesApi.java
- worker-message-prioritization-rabbitmq/src/main/java/com/github/workerframework/workermessageprioritization/rabbitmq/NodesApiImpl.java
- worker-message-prioritization-rabbitmq/src/main/java/com/github/workerframework/workermessageprioritization/rabbitmq/QueueNotFoundException.java
- worker-message-prioritization-rabbitmq/src/main/java/com/github/workerframework/workermessageprioritization/rabbitmq/QueuesApiImpl.java
- worker-message-prioritization-rabbitmq/src/main/java/com/github/workerframework/workermessageprioritization/rabbitmq/RabbitManagementApi.java
- worker-message-prioritization-rerouting/pom.xml
- worker-message-prioritization-rerouting/src/main/java/com/github/workerframework/workermessageprioritization/rerouting/MessageRouter.java
- worker-message-prioritization-rerouting/src/main/java/com/github/workerframework/workermessageprioritization/rerouting/MessageRouterSingleton.java
- worker-message-prioritization-rerouting/src/main/java/com/github/workerframework/workermessageprioritization/rerouting/StagingQueueCreator.java
- worker-message-prioritization-rerouting/src/test/java/com/github/workerframework/workermessageprioritization/rerouting/MessageRouterTests.java
- worker-message-prioritization-rerouting/src/test/java/com/github/workerframework/workermessageprioritization/rerouting/RerouterTestBase.java
- worker-message-prioritization-rerouting/src/test/java/com/github/workerframework/workermessageprioritization/rerouting/StagingQueueCreatorIT.java
- worker-message-prioritization-target-capacity-calculators/src/main/java/com/github/workerframework/workermessageprioritization/targetqueue/QueueInformationProvider.java
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=870109
> US870109: CVE-2023-0833: Update okhttp to jersey

- worker-message-prioritization-rerouting/src/test/java/com/github/workerframework/workermessageprioritization/rerouting/RerouterTestBase.java
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=870109
> US870109: Fix compilation issue

- worker-message-prioritization-rabbitmq/pom.xml
- worker-message-prioritization-rabbitmq/src/main/java/com/github/workerframework/workermessageprioritization/rabbitmq/RabbitManagementApi.java
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=870186
> I870186: Force jersey client to use Gson

- pom.xml
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=897102
> US897102: Update dependency versions

- worker-message-prioritization-distribution/src/main/java/com/github/workerframework/workermessageprioritization/redistribution/DistributorModule.java
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=887031
> US887031: Set fixed version of TLS

- pom.xml
- worker-message-prioritization-distribution-container/pom.xml
- worker-message-prioritization-distribution-container/src/test/docker/Dockerfile
- worker-message-prioritization-distribution/pom.xml
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=888096
> US888096: Use docker image version management plugin

- pom.xml
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=913065
> US913065: Update to latest base image release

- pom.xml
- release-notes-2.0.2.md
- worker-message-prioritization-distribution-container/pom.xml
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=916203
> US916203: Dependency updates for CVE resolution

- pom.xml
- worker-message-prioritization-distribution-container/pom.xml
- worker-message-prioritization-distribution-container/src/test/java/com/github/workerframework/workermessageprioritization/redistribution/DistributorIT.java
- worker-message-prioritization-distribution/pom.xml
- worker-message-prioritization-distribution/src/test/java/com/github/workerframework/workermessageprioritization/redistribution/LowLevelDistributorIT.java
- worker-message-prioritization-distribution/src/test/java/com/github/workerframework/workermessageprioritization/redistribution/consumption/ConsumptionTargetCalculatorBaseTest.java
- worker-message-prioritization-distribution/src/test/java/com/github/workerframework/workermessageprioritization/redistribution/consumption/EqualConsumptionTargetCalculatorTest.java
- worker-message-prioritization-distribution/src/test/java/com/github/workerframework/workermessageprioritization/redistribution/consumption/FastLaneConsumptionTargetCalculatorTest.java
- worker-message-prioritization-distribution/src/test/java/com/github/workerframework/workermessageprioritization/redistribution/consumption/QueueWeightEnvVariableCollectorTest.java
- worker-message-prioritization-distribution/src/test/java/com/github/workerframework/workermessageprioritization/redistribution/consumption/StagingQueueWeightSettingsTest.java
- worker-message-prioritization-rabbitmq/pom.xml
- worker-message-prioritization-target-capacity-calculators/pom.xml
- worker-message-prioritization-target-capacity-calculators/src/test/java/com/github/workerframework/workermessageprioritization/redistribution/HistoricalConsumptionRateManagerTest.java
- worker-message-prioritization-target-capacity-calculators/src/test/java/com/github/workerframework/workermessageprioritization/redistribution/MinimumConsumptionTargetCalculatorTest.java
- worker-message-prioritization-target-capacity-calculators/src/test/java/com/github/workerframework/workermessageprioritization/redistribution/TargetQueueLengthRounderTest.java
- worker-message-prioritization-target-capacity-calculators/src/test/java/com/github/workerframework/workermessageprioritization/redistribution/TunedTargetQueueLengthProviderTest.java
- worker-message-prioritization-target-capacity-calculators/src/test/java/com/github/workerframework/workermessageprioritization/targetqueue/K8sTargetQueueSettingsProviderTest.java
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=914108
> US914108: Version Currency: JUnit 5 migration

- pom.xml
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=922365
> I922365: Fix dynamic image tags

- pom.xml
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=920085
> US920085: Update to latest base image release

- pom.xml
- release-notes-2.1.0.md
- worker-message-prioritization-distribution-container/pom.xml
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=929026
> US929026: Updated to run on Java 21

- release-notes-2.1.0.md
- worker-message-prioritization-distribution-container/README.md
- worker-message-prioritization-distribution-container/pom.xml
- worker-message-prioritization-distribution-container/src/test/java/com/github/workerframework/workermessageprioritization/redistribution/DistributorIT.java
- worker-message-prioritization-distribution-container/src/test/java/com/github/workerframework/workermessageprioritization/redistribution/DistributorTestBase.java
- worker-message-prioritization-distribution/pom.xml
- worker-message-prioritization-distribution/src/main/java/com/github/workerframework/workermessageprioritization/redistribution/DistributorModule.java
- worker-message-prioritization-distribution/src/main/java/com/github/workerframework/workermessageprioritization/redistribution/MessageDistributor.java
- worker-message-prioritization-distribution/src/main/java/com/github/workerframework/workermessageprioritization/redistribution/config/MessageDistributorConfig.java
- worker-message-prioritization-distribution/src/main/java/com/github/workerframework/workermessageprioritization/redistribution/lowlevel/LowLevelDistributor.java
- worker-message-prioritization-distribution/src/test/java/com/github/workerframework/workermessageprioritization/redistribution/LowLevelDistributorIT.java
- worker-message-prioritization-distribution/src/test/java/com/github/workerframework/workermessageprioritization/redistribution/TunedTargetQueueIT.java
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=946052
> US946052: Create target queues if they do not exist

- pom.xml
- release-notes-2.1.0.md
- worker-message-prioritization-distribution-container/pom.xml
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=952036
> US952036: Oracle Linux Base Images: Update services to OracleLinux

- pom.xml
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=956022
> US956022: Update to latest base image release

- pom.xml
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=974026
> US974026: Updated to latest base image release

- pom.xml
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=969125
> US969125: Update caf-kubernetes-client to rel ver

- release-notes-2.1.0.md
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=970103
> US970103: Release prep

- pom.xml
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=969006
> US969006: Update commons-lang:3.17.0

- worker-message-prioritization-distribution-container/README.md
- worker-message-prioritization-distribution-container/pom.xml
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=974184
> US974184: Add use of JVM memory settings

- pom.xml
- release-notes-2.2.0.md
- worker-message-prioritization-distribution/pom.xml
- worker-message-prioritization-distribution/src/main/java/com/github/workerframework/workermessageprioritization/redistribution/config/MessageDistributorConfig.java
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=969005
> US969005: Read file-based secrets in Java process

- pom.xml
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=977107
> US977107: Updated to latest base image release

- release-notes-2.3.0.md
- worker-message-prioritization-distribution/src/main/java/com/github/workerframework/workermessageprioritization/redistribution/DistributorModule.java
- worker-message-prioritization-distribution/src/main/java/com/github/workerframework/workermessageprioritization/redistribution/config/MessageDistributorConfig.java
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=1016047
> US1016047: Introduce configurable TLS protocol version env var

- pom.xml
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=1027097
> US1027097: Update to latest base image release

- release-notes-2.3.2.md
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=1041049
> US1041049: Release prep

- pom.xml
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=1009117
> US1009117: Remove reliance on large messages being supported 
